// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: anki_vector/messaging/extensions.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// Copyright (c) 2018 Anki, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License in the file LICENSE.txt or at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Add a decorator for streamed message handling in app

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

// MARK: - Extension support defined in extensions.proto.

// MARK: - Extension Properties

// Swift Extensions on the exteneded Messages to add easy access to the declared
// extension fields. The names are based on the extension field name from the proto
// declaration. To avoid naming collisions, the names are prefixed with the name of
// the scope where the extend directive occurs.

extension SwiftProtobuf.Google_Protobuf_MessageOptions {

  public var Anki_Vector_ExternalInterface_streamed: Bool {
    get {return getExtensionValue(ext: Anki_Vector_ExternalInterface_Extensions_streamed) ?? false}
    set {setExtensionValue(ext: Anki_Vector_ExternalInterface_Extensions_streamed, value: newValue)}
  }
  /// Returns true if extension `Anki_Vector_ExternalInterface_Extensions_streamed`
  /// has been explicitly set.
  public var hasAnki_Vector_ExternalInterface_streamed: Bool {
    return hasExtensionValue(ext: Anki_Vector_ExternalInterface_Extensions_streamed)
  }
  /// Clears the value of extension `Anki_Vector_ExternalInterface_Extensions_streamed`.
  /// Subsequent reads from it will return its default value.
  public mutating func clearAnki_Vector_ExternalInterface_streamed() {
    clearExtensionValue(ext: Anki_Vector_ExternalInterface_Extensions_streamed)
  }

}

// MARK: - File's ExtensionMap: Anki_Vector_ExternalInterface_Extensions_Extensions

/// A `SwiftProtobuf.SimpleExtensionMap` that includes all of the extensions defined by
/// this .proto file. It can be used any place an `SwiftProtobuf.ExtensionMap` is needed
/// in parsing, or it can be combined with other `SwiftProtobuf.SimpleExtensionMap`s to create
/// a larger `SwiftProtobuf.SimpleExtensionMap`.
public let Anki_Vector_ExternalInterface_Extensions_Extensions: SwiftProtobuf.SimpleExtensionMap = [
  Anki_Vector_ExternalInterface_Extensions_streamed
]

// Extension Objects - The only reason these might be needed is when manually
// constructing a `SimpleExtensionMap`, otherwise, use the above _Extension Properties_
// accessors for the extension fields on the messages directly.

public let Anki_Vector_ExternalInterface_Extensions_streamed = SwiftProtobuf.MessageExtension<SwiftProtobuf.OptionalExtensionField<SwiftProtobuf.ProtobufBool>, SwiftProtobuf.Google_Protobuf_MessageOptions>(
  _protobuf_fieldNumber: 60000,
  fieldName: "Anki.Vector.external_interface.streamed"
)
