default_platform(:ios)

platform :ios do
  desc "iVector TestFlight beta build"
  lane :beta do
    #build_app
    build_app(scheme: "iVector (iOS)",
            configuration: "Release", 
            export_method: "ad-hoc", 
            export_options: {
              compileBitcode: true,
              method: "ad-hoc",
              provisioningProfiles: { 
                "com.mirfirstsnow.ivector" => "iVector"
              }
            }
    )
    increment_build_number
  end
  
  desc "Run tests and create a unit-test report"
  lane :tests do
	spm(
 	 command: "test",
  	 package_path: "Features",
  	 configuration: "release"
	)

	spm(
 	 command: "test",
  	 package_path: "Connection",
  	 configuration: "release"
	)

	spm(
 	 command: "test",
  	 package_path: "Components",
  	 configuration: "release"
	)
  end

end

